/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'addcreative': RouteRecordInfo<'addcreative', '/addcreative', Record<never, never>, Record<never, never>>,
    'creatives': RouteRecordInfo<'creatives', '/creatives', Record<never, never>, Record<never, never>>,
    'editcampaign': RouteRecordInfo<'editcampaign', '/editcampaign', Record<never, never>, Record<never, never>>,
    'editcreative': RouteRecordInfo<'editcreative', '/editcreative', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'newcampaign': RouteRecordInfo<'newcampaign', '/newcampaign', Record<never, never>, Record<never, never>>,
    'reg': RouteRecordInfo<'reg', '/reg', Record<never, never>, Record<never, never>>,
    'stats': RouteRecordInfo<'stats', '/stats', Record<never, never>, Record<never, never>>,
  }
}
